### ISSUE TITLE
CSS namespace tests use invalid CSS

### ISSUE THREAD

**Issue by mattbasta** [ben-eb/css-minifier-tests#3]
The tests in suite 079 and 080 use namespaces incorrectly:

```css
@namespace html "http://www.w3.org/1999/xhtml";
@namespace islands "http://bar.yandex.ru/ui/islands";

*|.test {
    color: red;
    margin: 0px;
}
```

`*|.test` is not a valid selector. The spec only allows element selectors to be placed immediately after the `|` character:

https://www.w3.org/TR/css3-selectors/#typenmsp

In these tests, a classname selector is used, which is invalid. The browser would conceivably drop the ruleset, or ignore the `*|` (or other namespace), meaning the "optimal" output would be to remove the ruleset entirely.

Perhaps replacing `.test` with a custom element name, like `custom-elem` would be better? It would be syntactically correct and be a good "real world" use case for namespaces.
